#
- name: Install python bindings for Selinux.
  # sudo: yes
  yum: name={{item}} state=present
  with_items:
  - libselinux-python
  - libsemanage-python

- name: Test to verify Selinux is running.
  command: getenforce
  changed_when: false