---
# tasks file for php
- name: Install PHP and Git.
  yum: name={{ item }} state=present
  with_items:
  - php
  - php-mysql
  - git

- name: Copy the code from repo.
  git: repo={{ repository }} dest=/var/www/html/

- name: Create the index.php file
  template: src=index.php.j2 dest=/var/www/html/index.php